Refactor datasets
bakajstep/KNN_Project2024 pull request #10
Opened 2024-03-29 16:57 UTC by bakajstep

2024-03-29 20:58 UTC, adamkankovsky requested changes
Moc hezky PR <3

2024-03-29 20:58 UTC, adamkankovsky commented on cnec2_ner_trainer.py
> +            ("validation.conll", sentences_validate)
Zde by podle me nemel byt validate, protoze zadny nema.

2024-03-29 20:58 UTC, adamkankovsky commented on parsers/cnec2_extended/cnec2_extended.py
> +            remove_files_by_extension(output_dir, '.txt')
Zde by se zadny .txt soubor nachazet nemel, protoze datasety jsou primo v conll

2024-03-29 20:58 UTC, adamkankovsky commented on requirements.txt
> +numpy~=1.26.4
Trochu se bojim aby tato zmena verzi fungovala na metacentru. Je potreba vyzkouset

2024-03-30 11:51 UTC, davidchocholaty commented
Na základě přidání #11 už lze tento PR taky mergnout.

2024-03-30 11:52 UTC, merged